name: GitHub CI

on:
  push:
    branches:
      - master
      - '6'
      - '7'
  pull_request:
    branches:
      - master
      - '6'
      - '7'

defaults:
  run:
    shell: 'bash -o errexit -o nounset -o pipefail {0}'

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - jdk8-jammy
          - jdk8-corretto
          - jdk8-ubi9
          - jdk11-jammy
          - jdk11-alpine
          - jdk11-corretto
          - jdk11-ubi9
          - jdk17-jammy
          - jdk17-noble
          - jdk17-alpine
          - jdk17-corretto
          - jdk17-ubi9
          - jdk17-jammy-graal
          - jdk17-noble-graal
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          cd "${{ matrix.directory }}"
          grep "FROM " Dockerfile | cut -d' ' -f2 | xargs -I{} docker pull {}
          docker build --tag "gradle:${{ matrix.directory }}" .
      - name: test
        env:
          expectedGradleVersion: '7.6.6'
        run: |
          if [[ "${{ matrix.directory }}" = *-and-current* ]]; then
            javaVersion=$(grep 'JAVA_CURRENT_HOME=' ${{ matrix.directory }}/Dockerfile | grep --extended-regex --only-matching '[0-9]+')
          else
            javaVersion=$(echo "${{ matrix.directory }}" | grep --extended-regex --only-matching 'jdk[0-9]+' | grep --extended-regex --only-matching '[0-9]+')
          fi
          if [[ "${{ matrix.directory }}" = *graal* ]]; then
            cd test-graal
            sed --in-place "s/JavaLanguageVersion.of(00)/JavaLanguageVersion.of(${javaVersion})/" app/build.gradle
          else
            cd test
            sed --in-place "s/JavaLanguageVersion.of(00)/JavaLanguageVersion.of(${javaVersion})/" lib/build.gradle.kts
          fi
          ./run.sh "gradle:${{ matrix.directory }}" "${expectedGradleVersion}"
